spring:
  config:
    activate:
      on-profile: docker

  cloud:
    gateway:
      # ---------- CORS (JWT HEADER BASED AUTH) ----------
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - Authorization
              - Content-Type
            exposedHeaders:
              - Authorization
            maxAge: 3600

# ---------- EUREKA ----------
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# ---------- ACTUATOR ----------
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - gateway

# ---------- LOGGING ----------
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: DEBUG
    org.springframework.web.cors: DEBUG
